### ISSUE TITLE
Outdated crx warning

### ISSUE THREAD

**Issue by sidoruk-sv** [johnagan/crx-webpack-plugin#2]
When installing this plugin, got 

```
deprecated crx@3.0.4: crx@3.2.0 now let you select a list of files and do not rely on temporary folder to pack your ZIP or CRX. Please upgrade! :-)
```

**Comment by monolithed** [comment]
+1

```
(node:83454) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
(node:83454) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:83454) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

**Comment by johnagan** [comment]
fixed in 0.1.5

**Comment by bartsmykla** [comment]
I'm still receiving this warning:

```
(node:77902) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:77902) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```
in
`"crx-webpack-plugin": "^0.1.5",`

**Comment by sidoruk-sv** [comment]
@tranotheron maybe try to remove node_modules folder `rm -rf node_modules` and do `npm cache clean`, after that reinstall packages. I tried this and no warnings appeared on `0.1.5`
